### ISSUE TITLE
Test dynamic scaling of clusters

### ISSUE THREAD

**Issue by gbbirkisson** [enonic/xp-operator#104]
What happens when we dynamically add/remove nodes from a XP cluster. Will the whole thing crash, or does XP handle that situation?

**Comment by danhul** [comment]
I tested a cluster resizing of XP on EU QA k8s cluster. Initially the cluster had 3 master nodes and 2 worker nodes. 
Then I edited the "worker" statefulset and changed the replica count of workers to 3. The cluster successfully added one additional pod to make the total number of nodes 3. I then tested cluster sizing change by setting the number of master node replicas to 5 by editing the master statefulset. The cluster managed to resize its size but admin page failed to respond on all of the initially setup nodes. On one of the initial worker nodes I get 503 but on the others the admin page is unresponsive. 

XP log from only one of the initial worker node (which is unresponsive to admin page) shows the warning shown below (In case it indicates what the issue is ). The other pods doesn't have any warning in logs.  I then started to restart the initial pods (worker and master nodes) and after restart each pod started responding to admin page requests. 

Cluster downsizing is also tested by changing from 8 nodes to 5 nodes (3 master and 2 workers)  and it works as expected.


```
2023-02-25 21:27:18,458 INFO  c.h.i.p.impl.MigrationManager - [10.28.4.16]:5701 [3.12.12#OSS] [3.12.12] Re-partitioning cluster data... Migration queue size: 229
2023-02-25 21:27:20,793 INFO  c.h.i.partition.impl.MigrationThread - [10.28.4.16]:5701 [3.12.12#OSS] [3.12.12] All migration tasks have been completed. (lastRepartitionTime=Sat Feb 25 21:27:18 GMT 2023, completedMigrations=229, totalCompletedMigrations=365, elapsedMigrationTime=1332ms, totalElapsedMigrationTime=2059ms)
2023-02-25 21:27:29,235 INFO  org.elasticsearch.cluster.service - [worker-0] added {{master-4}{ILEsZakHTsiZKHJb6qr9ew}{10.28.5.15}{10.28.5.15:9300}{data=false, local=false, master=true},}, reason: zen-disco-receive(from master [{master-0}{KBJeyaDJQ5CcETYmIcODUA}{10.28.5.13}{10.28.5.13:9300}{data=false, local=false, master=true}])
2023-02-25 21:27:30,255 INFO  org.elasticsearch.cluster.service - [worker-0] added {{master-3}{p5YaYIViT7ec6ZzPVOyUgw}{10.28.4.17}{10.28.4.17:9300}{data=false, local=false, master=true},}, reason: zen-disco-receive(from master [{master-0}{KBJeyaDJQ5CcETYmIcODUA}{10.28.5.13}{10.28.5.13:9300}{data=false, local=false, master=true}])
2023-02-25 21:30:22,923 WARN  c.e.x.admin.event.impl.EventEndpoint - Errored websocket 2
org.eclipse.jetty.websocket.api.CloseException: java.util.concurrent.TimeoutException: Idle timeout expired: 300000/300000 ms
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:564)
	at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:172)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:539)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:317)
	at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:140)
	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:407)
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171)
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor
![Screenshot 2023-02-25 at 22 39 04](https://user-images.githubusercontent.com/35296291/221382400-9f2d5c1a-6c9e-4c3e-b45a-8799785d10a8.png)

![Screenshot 2023-02-25 at 22 23 21](https://user-images.githubusercontent.com/35296291/221382397-9e070258-5948-44fc-9226-4f4722f6092b.png)
.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 300000/3
![Screenshot 2023-02-25 at 22 37 44](https://user-images.githubusercontent.com/35296291/221382388-2a40f330-8c23-4888-99f8-9a19dc808438.png)
00000 ms
	... 8 common frames omitted
```

**Comment by danhul** [comment]
![Screenshot 2023-02-25 at 22 39 04](https://user-images.githubusercontent.com/35296291/221382490-5195b2bb-235f-4afb-86e5-288a712745c2.png)
![Screenshot 2023-02-25 at 22 37 44](https://user-images.githubusercontent.com/35296291/221382497-085e3417-6152-481d-9c23-133177faba30.png)
![Screenshot 2023-02-25 at 22 23 21](https://user-images.githubusercontent.com/35296291/221382501-0b7c1e49-eaa6-4c0a-a85e-18f0f8653123.png)
