### ISSUE TITLE
Routes class cast problem

### ISSUE THREAD

**Issue by edloidas** [enonic/xp-operator#284]
`class okio.RealBufferedSource` is not castable to `Xp7MgmtRoutesList` after java-client version `0.17.12`.

When the Cloud API sends the `resourcesSuggestions` request via operator, result is no longer properly casted.

Stack trace:
```log
2022-08-19 11:47:33,394 WARN  n.g.e.SimpleDataFetcherExceptionHandler - Exception while fetching data (/resourcesSuggestions) : class okio.RealBufferedSource$1 cannot be cast to class com.enonic.kubernetes.client.v1.api.xp7.routes.Xp7MgmtRoutesList (okio.RealBufferedSource$1 and com.enonic.kubernetes.client.v1.api.xp7.routes.Xp7MgmtRoutesList are in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @43cf3e73)
java.lang.ClassCastException: class okio.RealBufferedSource$1 cannot be cast to class com.enonic.kubernetes.client.v1.api.xp7.routes.Xp7MgmtRoutesList (okio.RealBufferedSource$1 and com.enonic.kubernetes.client.v1.api.xp7.routes.Xp7MgmtRoutesList are in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @43cf3e73)
        at com.enonic.kubernetes.client.v1.api.xp7.mgmt.Xp7MgmtApiRoutesImpl.list(Xp7MgmtApiRoutesImpl.java:13)
        at com.enonic.cloud.api.k8s.K8SXp7ClientImpl.routes(K8SXp7ClientImpl.java:32)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$2046$194966A$graphql.L:1#\==\_\!1#\==\_\!5102#createXp7Client#routes(com.enonic.cloud.api:/services/graphql/graphql.js:5179)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$2043$267091A$graphql.L:1#\==\_\!1#L:6495#getSuggestedRoutes(com.enonic.cloud.api:/services/graphql/graphql.js:6839)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$2023$461851A$graphql.L:1#\==\_\!1#L:11587#suggestResources(com.enonic.cloud.api:/services/graphql/graphql.js:11732)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$2022$438151A$graphql.L:1#\==\_\!1#\==\_\!11085#resolve-7(com.enonic.cloud.api:/services/graphql/graphql.js:11168)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:657)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:120)
        at com.enonic.xp.script.impl.value.FunctionScriptValue.call(FunctionScriptValue.java:38)
        at com.enonic.lib.graphql.GraphQlBean.lambda$setFieldData$5(GraphQlBean.java:268)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:279)
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:210)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60)
        at graphql.execution.Execution.executeOperation(Execution.java:159)
        at graphql.execution.Execution.execute(Execution.java:105)
        at graphql.GraphQL.execute(GraphQL.java:613)
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:538)
        at graphql.GraphQL.executeAsync(GraphQL.java:502)
        at graphql.GraphQL.execute(GraphQL.java:433)
        at com.enonic.lib.graphql.GraphQLHandler.execute(GraphQLHandler.java:46)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1834$4520AAAA$graphql.L:1#execute(com.enonic.cloud.api:/lib/graphql.js:111)
        at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1830$495611A$graphql.L:1#\==\_\!1#\==\_\!12563#post(com.enonic.cloud.api:/services/graphql/graphql.js:12585)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:657)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
        at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
        at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:120)
        at com.enonic.xp.script.impl.value.FunctionScriptValue.call(FunctionScriptValue.java:38)
        at com.enonic.xp.script.impl.executor.ScriptExportsImpl.executeMethod(ScriptExportsImpl.java:59)
        at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.doExecute(ControllerScriptImpl.java:71)
        at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.lambda$execute$0(ControllerScriptImpl.java:36)
        at com.enonic.xp.trace.Tracer.traceEx(Tracer.java:72)
        at com.enonic.xp.trace.Tracer.trace(Tracer.java:51)
        at com.enonic.xp.trace.Tracer.trace(Tracer.java:98)
        at com.enonic.xp.portal.impl.controller.ControllerScriptImpl.execute(ControllerScriptImpl.java:36)
        at com.enonic.xp.portal.impl.handler.service.ServiceHandlerWorker.execute(ServiceHandlerWorker.java:101)
        at com.enonic.xp.portal.impl.handler.service.ServiceHandler.doHandle(ServiceHandler.java:65)
        at com.enonic.xp.portal.impl.handler.service.ServiceHandler.doHandle(ServiceHandler.java:24)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:66)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.portal.impl.handler.mapping.MappingHandler.handle(MappingHandler.java:84)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:75)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.portal.handler.BasePortalHandler.doHandle(BasePortalHandler.java:46)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:66)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.web.impl.trace.TraceWebFilter.doHandle(TraceWebFilter.java:38)
        at com.enonic.xp.web.handler.BaseWebHandler.handle(BaseWebHandler.java:66)
        at com.enonic.xp.web.impl.handler.WebHandlerChainImpl.handle(WebHandlerChainImpl.java:28)
        at com.enonic.xp.web.impl.handler.WebDispatcherImpl.dispatch(WebDispatcherImpl.java:35)
        at com.enonic.xp.web.impl.handler.WebDispatcherServlet.doHandle(WebDispatcherServlet.java:140)
        at com.enonic.xp.web.impl.handler.WebDispatcherServlet.service(WebDispatcherServlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.enonic.xp.web.impl.dispatch.mapping.ServletDefinitionImpl.service(ServletDefinitionImpl.java:40)
        at com.enonic.xp.web.impl.dispatch.pipeline.ServletPipelineImpl.service(ServletPipelineImpl.java:38)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:51)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
        at com.enonic.xp.portal.impl.idprovider.IdProviderFilter.doHandle(IdProviderFilter.java:46)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:42)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
        at com.enonic.xp.web.impl.context.ContextFilter.lambda$doHandle$0(ContextFilter.java:34)
        at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:100)
        at com.enonic.xp.web.impl.context.ContextFilter.doHandle(ContextFilter.java:33)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:42)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
        at com.enonic.xp.web.vhost.impl.VirtualHostFilter.doHandle(VirtualHostFilter.java:73)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:42)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
        at com.enonic.xp.web.impl.dos.DosFilterWrapper.doFilter(DosFilterWrapper.java:65)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:42)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
        at org.eclipse.jetty.servlets.HeaderFilter.doFilter(HeaderFilter.java:117)
        at com.enonic.xp.web.impl.header.HeaderFilterWrapper.doHandle(HeaderFilterWrapper.java:51)
        at com.enonic.xp.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:31)
        at com.enonic.xp.web.filter.BaseWebFilter.doFilter(BaseWebFilter.java:33)
        at com.enonic.xp.web.impl.dispatch.mapping.FilterDefinitionImpl.doFilter(FilterDefinitionImpl.java:41)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:42)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterChainImpl.doFilter(FilterChainImpl.java:33)
        at com.enonic.xp.web.impl.dispatch.pipeline.FilterPipelineImpl.filter(FilterPipelineImpl.java:37)
        at com.enonic.xp.web.impl.dispatch.DispatchServletImpl.service(DispatchServletImpl.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:722)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by edloidas** [comment]
I can now confirm, that the error is gone in Cloud API, when using operator `0.18`.
